### PR TITLE
get image back now and can get properties from image

### PR DESCRIPTION
**Pull request by lexusburn**

### CODE REVIEW

**Comment by jcupitt** [comment]
\o/

**Comment by lexusburn** [comment]
Merged your latest version into mine and found out what the problem was that i had with the insert.
I thought that it would merge both images and i can get the second image as watermark upon first image, but it only places the second image on given position without merging it with the underlaying.
Had seen that someone other had requested it and you put a combine-method on the roadmap for next version. :-)

**Comment by jcupitt** [comment]
Ah OK, yes, insert just does a paste, it doesn't try to blend.

To blend a watermark into an image, you `crop` out the section of the big image you want to blend the watermark into, use `ifthenelse` with `blend = TRUE` to fade the watermark in with the alpha, then `insert` the blended image back into the big one. It should be three lines of lua when this binding is done. 

That enhancement is for something to blend a whole stack of images in a single operation. It doesn't really add a feature, just a fast (hopefully) shortcut.

**Comment by lexusburn** [comment]
Ok, now i had it! \o/

I had to do these steps:
- get alpha channel from watermark
- extract the part from background image where i want to place watermark
- call ifthenelse with alphachannel as condition, watermark as image1, extract as image2 and blend true
- insert return from iftehnelse into background

Seems to work. :-)

Next steps for me: implement resize and rotate.

**Comment by jcupitt** [comment]
Nice! 

I'll keep fiddling with the introspection stuff. If we can get that working, we can generate the whole binding automatically.

**Comment by jcupitt** [comment]
Oh haha I just found this:

https://github.com/pavouk/lgi

We could use this to call libvips directly, no need to write our own thing. 

I might keep trying anyway. I like the ffi approach, and it would be simpler than going via a native layer.

**Comment by lexusburn** [comment]
That means, that it’s not necessary to create lua methods for each vips method by hand?
That sounds great! :-)

**Comment by jcupitt** [comment]
That's right, we should be able to just add an `__index` method to image which calls the right vips operation automatically. It should handle all the arguments and optional arguments automatically too.

**Comment by lexusburn** [comment]
What can i do to help you regarding the introspection?
That sounds really cools, because new or changed vips methods can be used without changing the connector if i understand it correctly.

**Comment by jcupitt** [comment]
Yes, that's right, all the libvips bindings are like that, they generate themselves automatically at runtime. The C++ one is static, sadly, but at least the source code for the C++ binding is generated by a script, not by hand.

The idea is that they don't need much maintenance, and because the API is so close to the C one (they are generated from the same data), you can just use the C docs. 

I've got the thing to get and set vips properties automatically working:

https://github.com/jcupitt/lua-vips-ffi/blob/john-experiment/experiment/test-vobject.lua

It makes a "black" operator, then gets and sets width. It looks up the "width" property, gets the type, and uses that information to change the lua types into the vips ones and back again.

I was going to try making a lua class for operation next, inheriting from object somehow, and then use `vips_argument_map` to get a list of all the operation arguments ready to be set from lua.

Do you want to try that? You'll need to make an ffi callback to pass to `vips_argument_map`.

http://jcupitt.github.io/libvips/API/current/VipsObject.html#vips-argument-map

**Comment by jcupitt** [comment]
I meant to say, I have some other stuff I need to work on for the next few days, so it's all yours.

I'm not sure what the best way to handle inheritance is. It would be nice if a voperation object could inherit from the vobject thing we have now (and not have to reimplement new/get/set). Likewise, when vimage is added, that should inherit from vobject as well.

I've been doing some experiments, but I've not been able to get ffi to link __index tables together yet between ffi metatypes.

**Comment by lexusburn** [comment]
Hello John,

i will have a look and try to implement it.
On this weekend i can do it only in a few hours, but next week i will have more time for it.
Thank your for your work and hints. Have a nice weekend!

Frederic

**Comment by jcupitt** [comment]
I had some time on the train, so I think I've got it working. You can now run:

```
local result = voperation.call("black", 100, 200, {bands = 3})
```

and it'll look up `black`, set with and height from the 100 and the 200, set bands from the option, call the operation, pull out the result and return the image. 

It needs a VipsImage connector next.

**Comment by jcupitt** [comment]
I did a bit more, this now works:

```lua
local vimage = require("vimage_connector")
image3 = vimage.black(1, 2, {bands = 3})
image4 = vimage.new_from_file("/home/john/pics/k2.jpg")
local height = image4:object():get("height")
print("height = ", height)
image4 = image4:invert()
image4:write_to_file("x.jpg")
```

It all uses introspection, so you can call any vips operation!

It only implements numbers, strings and images as param types, that needs fixing. 

The type names probaly need sorting out. What's the lua convention? Most languages will use initial caps for class names or constructors.

Overloads would be fun, so you could write `image3 = image1 + image2`.

Buffer input and output needs doing, so `image = vimage.new_from_buffer(".jpg", str)` to load from a string.

I swear I won't touch it again today.

**Comment by lexusburn** [comment]
In one wird: wow... That's great. I though you had no time for it?

**Comment by jcupitt** [comment]
I finished the other thing I had to do sooner than I thought, then had some time on a train journey. Anyway ... it's all yours for a while.

**Comment by lexusburn** [comment]
:-)

I’m trying to implement the load_from_buffer and save_to_buffer methods

**Comment by jcupitt** [comment]
I did a bit more, these all work now:

```
image4 = vimage.new_from_file("/home/john/pics/k2.jpg")
image1 = image4 + image4
image1 = image4 + 12
image1 = image4 + {40, 0, -12}
local height = image:height()
```

Adding a table to an image adds to bands separately, so `+ {40, 0, -12}` adds 40 to red and subtracts 12 from blue.

Results are now returned as arrays, not tables, so this works:

```
max_value = image4:max()
max_value, x, y, outs, xes, yes = image4:max{size = 10}
```

ie. you get all the outputs back, and you can just pick the ones you want.

I'm going to merge this to master and clean it up a bit. I think more development should happen there, with a fresh set of issues.

**Comment by jcupitt** [comment]
OK, renamed as plain lua-vips, made a luarocks package, and made a hello world example:

https://github.com/jcupitt/lua-vips

All new development in issues over there. Phew!

**Pull request merged**
